version: '3'
services:
  # NGINX server
  vwa-nginx:
    image: victorhad/accounts:nginx
    container_name: vwa-server
    build:
      context: .
      dockerfile: ./enviroments/nginx/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - vwa

  # VWA production app
  vwa:
    image: victorhad/accounts:latest
    container_name: vwa
    build:
      context: .
      dockerfile: ./enviroments/production/Dockerfile
    depends_on:
      - db

  # Postgresql database
  db:
    image: postgres:latest
    container_name: vwa-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db